### ISSUE TITLE
How to search both ibeacon and alt-beacon using RNLbeacon in ios? 

### ISSUE THREAD

**Issue by sukh1993** [AltBeacon/ios-beacon-tools#10]
i am using RNLBeacon sdk in my project, it detect only Alt beacon not i beacon. i want both. if you have any suggestion please let me know.

**Comment by sukh1993** [comment]
laterly i used setlayout func for ibeacon search.
 RNLBeaconParser *iBeaconParser = [[RNLBeaconParser alloc] init];
    [iBeaconParser setBeaconLayout:@"m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24" error:Nil];
    
    self.beaconParsers = @[ altBeaconParser, uidBeaconParser, urlBeaconParser, eidBeaconParser, tlmBeaconParser, iBeaconParser];

but its no working..

**Comment by davidgyoung** [comment]
Sorry, you cannot detect iBeacon with the code in this project.  This project uses CoreBluetooth APIs and unfortunately Apple blocks the ability to detect iBeacon with CoreBluetooth APIs.  To detect iBeacon you must use CoreLocation APIs, meaning you must use this project for detecting all beacon types besides iBeacon and CoreLocation  for iBeacon.
