### ISSUE TITLE
I need to restart bluetooth to detect beacon

### ISSUE THREAD

**Issue by vanessa05** [AltBeacon/ios-beacon-tools#11]
I use a code similar to the one indicated in the README file.

At the beginning, no beacon appears in the trackedBeacons list. I need to stop the bluetooth and restart it for them to appear. Do you have an explanation for this? thank you in advance for your help

**Comment by davidgyoung** [comment]
Do you call `scanner?.startScanning()`?  If so and the bluetooth stack is in a functional state, it should work immediately.

The code listens for bluetooth power cycle events and whenever bluetooth is in a powered on state, it restarts scanning.  This might explain why you see it start working after power cycling bluetooth.  But it doesn't explain why it doesn't work when you initially call `startScanning()` unless the bluetooth stack had been in a bad state when that call was made.

**Comment by vanessa05** [comment]
Thank you @davidgyoung for your answer but yes, I do call scanner?.startScanning().
It was a big problem for me so I changed : I user now Kontakt library and all is ok.
