### ISSUE TITLE
Background detection

### ISSUE THREAD

**Issue by awazgyawali** [AltBeacon/ios-beacon-tools#13]
I use this project to scan beacons, and I need to continue scanning even if the app goes to the background. The case I am having, the iPhone will not go to sleep or lock the screen but the user is supposed to go to google maps navigation screen and again come back to my app. While my app is in the background and google map is in the foreground, I still want my app to detect beacons and play a sound that I am doing currently on android using the alt beacon library. Is this possible by activating background modes or we cannot add this feature at all using CoreBluetooth?

**Comment by cimplesid** [comment]
@awazgyawali I was doing similar stuff any solution yet ?

**Comment by cimplesid** [comment]
i think issue can be closed
