### ISSUE TITLE
Unable to detect iBeacon format

### ISSUE THREAD

**Issue by KeithGapusan** [AltBeacon/ios-beacon-tools#16]
Hello, I was trying the sample code to scan nearby beacons. My can detect altbeacon an eddystore, however on the library cannot detect ibeacon format. Can i ask if did i missed something? thanks

` 
func getBeacons(_ completed: @escaping(_ list: [RNLBeacon]) -> ()){

        if let detectedBeacons = scanner?.trackedBeacons() as? [RNLBeacon] {
            self.detectedBeacon = detectedBeacons
            completed(detectedBeacons)
            for beacon in detectedBeacons {
                if (beacon.beaconTypeCode.intValue == 0xbeac) {
                    // this is an AltBeacon
                    NSLog("Detected AltBeacon id1: %@ id2: %@ id3: %@", beacon.id1, beacon.id2, beacon.id3)
                }
                else if (beacon.beaconTypeCode.intValue == 0x00 && beacon.serviceUuid.intValue == 0xFEAA) {
                    // this is eddystone uid
                    NSLog("Detected EDDYSTONE-UID with namespace %@ instance %@", beacon.id1, beacon.id2)
                }
                else if (beacon.beaconTypeCode.intValue == 0x10 && beacon.serviceUuid.intValue == 0xFEAA) {
                    // this is eddystone url
                    NSLog("Detected EDDYSTONE-URL with %@", RNLURLBeaconCompressor.urlString(fromEddystoneURLIdentifier: beacon.id1))
                }
                else {
                    NSLog("Some other beacon detectd")
                    // some other beacon type
                }
                NSLog("The beacon is about %.1f meters away", beacon.distance)
            }
        }

    }
`

**Comment by davidgyoung** [comment]
You cannot use this code to detect the iBeacon format, because Apple intentionally filters out iBeacon packets from the scans visible by CoreBluetooth APIs, and this code uses CoreBluetooth APIs to do the scanning.
