### ISSUE TITLE
It Only broadcast Never scan others

### ISSUE THREAD

**Issue by ritesh124** [AltBeacon/ios-beacon-tools#3]
Only Once it has worked but never before n never after, However it is broadcasting beacon in background also.
But this does not solve the problem as the beacon has to always scan for the another user(Even if there is no interent)

**Comment by davidgyoung** [comment]
@ritesh124, sorry, I don't think I understand the specific problem you are reporting.  Please report (a) precisely what you expect to see and (b) what you see instead that is not expected.  Please show any sample code and describe any conditions you need to reproduce the problem.
