### ISSUE TITLE
Method name should be change

### ISSUE THREAD

**Issue by sumit-vuliv** [AltBeacon/ios-beacon-tools#5]
Hi we have downloaded this code as run as per the guideline mentioned ion the project but once we run this project it start to give the error says 'startScanning ,stopscanning' not implemented. but when we have changed the method name startscanningAltbeacon then it start to work like charm.

**Comment by EddieLukeAtmey** [comment]
Lol it was in this commit: 
https://github.com/AltBeacon/ios-beacon-tools/commit/2618a9b5d48f57823516e2b9afa187cc1428fc14

They changed the name (both the calling and header) but forgot to rename the implementaion function

**Comment by davidgyoung** [comment]
I'd welcome a pull request to fix this

**Comment by EddieLukeAtmey** [comment]
#6

**Comment by EddieLukeAtmey** [comment]
Oh no, PR#4 is a reverse version of PR#6. You either choose one, not both. Since you merged both, the issue raise again but with a different error:

`startScanningAltbeacons , stopScanningAltbeacons not implemented`

I suggest you revert merged#4, to avoid as much error as possible

**Comment by davidgyoung** [comment]
Yep, you are right, @EddieLukeAtmey, I misread #6.  Sorry about that.  #4 is reverted now.
