### ISSUE TITLE
How to get stable signal strength (RSSI) between the device and the beacon

### ISSUE THREAD

**Issue by RuchiraMore** [AltBeacon/ios-beacon-tools#9]
Please help in to maintain the signal strength (RSSI) between the device and the beacon. 
If I have placed it near and again changed its position then it should took lesser time to get stable and show approximately stable distance in less time.

**Comment by davidgyoung** [comment]
How long do you see it take for the distance estimate to stabilise?

**Comment by davidgyoung** [comment]
closed due to inactivity.
